// <auto-generated />
namespace PluSystemVolunteer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lista : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lista));
        
        string IMigrationMetadata.Id
        {
            get { return "201907040012461_lista"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
